version: "3"

services:

    rest-service:
        env_file: flask-jwt-auth/.env
        container_name: rest-service
        build:
          context: flask-jwt-auth
          dockerfile: Dockerfile
          args:
            ENV_FILE: .env
            BASE_DIR: /flask-jwt-auth
        # Migrating the database in the command where the server is runned is dangerous but
        # in this case simplifies execution
        command:  flask run -h 0.0.0.0 -p 5000
        volumes:
          - ./flask-jwt-auth:/flask-jwt-auth
        ports:
          - "5000:5000"
    
    frontend:
        env_file: reactjs-jwt-authentication/.env
        container_name: frontend
        build:
          context: reactjs-jwt-authentication
          dockerfile: Dockerfile
          args:
            ENV_FILE: .env
            BASE_DIR: /reactjs-jwt-authentication
        command:  /command.sh
        volumes:
          - ./reactjs-jwt-authentication:/reactjs-jwt-authentication
          - ./reactjs-jwt-authentication/command.sh:/command.sh
        ports:
          - "8080:8080"
        depends_on:
          - rest-service