version: "3"

services:

    rest-service:
        env_file: flask-jwt-auth/.env
        container_name: rest-service
        build:
          context: flask-jwt-auth
          dockerfile: Dockerfile
          args:
            ENV_FILE: .env
            BASE_DIR: /flask-jwt-auth
        # Migrating the database in the command where the server is runned is dangerous but
        # in this case simplifies execution
        command:  /command.sh
        volumes:
          - ./flask-jwt-auth:/flask-jwt-auth
          - ./flask-jwt-auth/command.sh:/command.sh
        # ports:
        #   - "5000:5000"
    
    frontend:
      env_file: reactjs-jwt-authentication/.env
      container_name: frontend
      build:
        context: reactjs-jwt-authentication
        dockerfile: Dockerfile
        args:
          ENV_FILE: .env
          BASE_DIR: /reactjs-jwt-authentication
      command:  /command.sh
      volumes:
        - ./reactjs-jwt-authentication:/reactjs-jwt-authentication
        - ./reactjs-jwt-authentication/command.sh:/command.sh
      ports:
        - "80:80"
      depends_on:
        - rest-service
      

    nginx-rest-service:
      image: rest-service-nginx
      build:
          context: flask-jwt-auth/nginx
          dockerfile: Dockerfile
          args:
            ENV_FILE: .env
            BASE_DIR: /flask-jwt-auth
      container_name: rest-service-nginx
      restart: always
      ports:
        - "90:90"
      depends_on:
        - rest-service